### ISSUE TITLE
Allow manual updating of online quotes on several equities simultaneously

### ISSUE THREAD

**Issue by KopolJunam** [portfolio-performance/portfolio#1499]
EDIT: OBSOLETE? I just saw that there is an online menu where one can do that what I want, so maybe adding this to the context menu is not really necessary, or is it?

As the users of the VIAC/CS quote feed know the Credit Suisse server sometimes doesn't answer and it takes several attempts or it has to be done at a non busy time (evening/weekend). This can be done easily by adding the quote update to the menu when there are multiple equities selected. At the moment a manual update is only possible on a single equity.
A keyboard shortcut could be welcome too for the poor VIAC users who sometimes have to try several times.

Btw, I tried several approaches to mitigate this problem but nothing really works so far. A comfortable manual updating feature might do the trick for most or at least for now.

@buchen I would implement this myself as it's probably a piece of cake if it's ok with you.

**Comment by buchen** [comment]
There is the menu entry, yes, but even if you select multiple securities, it updates only one.

The reason is that my "central selection" can only have one security. This is not easy to change unfortunately.

What is probably much easier to enhance the context menu of the SecuritiesTable to also show the option "Update online quotes" if multiple securities are selected. Feel free to submit a change.

**Comment by pfalcon** [comment]
> Allow manual updating of online quotes on several equities simultaneously

https://github.com/portfolio-performance/portfolio/pull/4212 implements just this.

**Comment by mierin12** [comment]
Done on [release 0.71.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.71.0) with https://github.com/portfolio-performance/portfolio/pull/4212
