### ISSUE TITLE
CSV import mixes up values if line break (multi line entry) and a certain template are involved

### ISSUE THREAD

**Issue by r-eis** [portfolio-performance/portfolio#2169]
**Describe the bug**
Values of a CSV get assigned to the wrong column if a multi-line cell value and a template are involved. It does not happen with any template, so I attached the template that produces the faulty behaviour.

**To Reproduce**
1. Press CTRL + I,C to open the CSV import's file chooser dialog
2. Select the file `booking-with-line-break.csv` (see zip attachment)
3. Scroll to the column called "Value" and see that it has a value of -21.85
3. Import the config file `csv-config.json` (see zip attachment) from the settings context menu of the dialog
4. Scroll to the column called "Value" and see that it does not have an assigned value any more. The value seems to get assigned to the "EntryText" column instead.

Unexpected screenshot:
![screenshot-after-importing-config](https://user-images.githubusercontent.com/62334634/111852892-0a01a600-8919-11eb-857d-c97e3b4ec1a2.jpg)

**Expected behavior**
The value -21,85 is in the "Value" column.

Expected screenshot:
![screenshot-before-importing-config](https://user-images.githubusercontent.com/62334634/111852565-b2166f80-8917-11eb-9916-a56798eb1133.jpg)

**Desktop**
 - OS: win32, x86_64
 - Version: 0.51.2

[csv-and-json.zip](https://github.com/buchen/portfolio/files/6174553/csv-and-json.zip)

**Comment by Nirus2000** [comment]
Hello @r-eis 
I have loaded your configuration and the CSV file and cannot recreate the problem. 
Can you please provide another example with a test CSV and Config ?

Regards
Alex

**Comment by Nirus2000** [comment]
Hello @r-eis 
i just test it again... here the files.
[csv-and-json-without-linebreak.zip](https://github.com/portfolio-performance/portfolio/files/12352474/csv-and-json-without-linebreak.zip)
Fix this your problem?!
![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/6e0affcf-4574-4243-8b1d-147ca2e78d78)

If it is DKB... you can import by PDF-Importer...

Regards
Alex

**Comment by Nirus2000** [comment]
Hello @r-eis 
I don't understand your theory or what the problem is. You need to assign the columns that you need.
If your export program keeps rearranging the columns, this can of course lead to problems. We just remember, column x is this value.
The headers are not relevant.

If you have PDF documents of the bank, then we can create a suitable PDF importer. For this we simply need several PDF's as PDF debug.

Regards
Alex

**Comment by Nirus2000** [comment]
Hello @r-eis 
> So I'm afraid, we have to assume that the order (and number) of columns can change in Banking4. Is the column order guaranteed by all the other CSVs you get when a CSV header is present?

The CSV importer doesn't look for the CSV header but remembers the column as a number.
Column 1 = date
Column 2 = Currency
Column 3 = Amount
....
This method is used depending on how you configure the columns.
In this way, you can store hundreds of configurations and load and save them as required.

---

> What do think about using the header labels instead of the column order to match between JSON and CSV?
If no header is available, one could fall back to the column order?

This configuration is universal as it is and otherwise it makes no sense since the logic would be duplicated and thus more of a problem than a solution. 
If your program keeps outputting different column arrangements, for whatever reason, then you just have to keep adjusting the CSV importer.
