### ISSUE TITLE
CoinGecko: Support for ambiguous ticker symbols

### ISSUE THREAD

**Issue by kasch-code** [portfolio-performance/portfolio#2464]
At the moment, the CoinGecko quote provider uses the specified ticker symbol, e.g. BTC for Bitcoin or ETH for Ethereum, to retrieve the quote data. To do this, the common ticker symbol is mapped to the internal CoinGecko ID first, which has to be used for all following API calls.

This leads to a problem, when a ticker symbol is assigned to multiple coins, for example BIT.

Possible solutions would be:
1. Use the CoinGecko ID instead of the common ticker in the security master data
2. Give the user the option to specify the CoinGecko ID _in addition_ to the ticker symbol for these cases

Drawback of option 1 is that this would be not very intuitive. The users are used to the common ticker symbols of the coins and not the CoinGecko ID. Furthermore this would break existing files using the provider.

Option 2 therefore would be preferred. The additional ID could either be stored in one of the unused fields for crypto (WKN, ISIN) or as an additional provider attribute in the "Latest Quote" screen. The latter would be preferred as it is a cleaner solution.
When the CoinGecko ID is provided, it will be used instead of the ticker symbol to retrieve the quotes from CoinGecko (no mapping will be done in this case).

Also see the comments in #2325 for further information.

**Comment by kasch-code** [comment]
I will have a look into this issue once I find some time. Please feel free to assign it to me.

**Comment by photobook-hive** [comment]
Hey Karsten, 

i think this would also work for my bug.

Gruß
Arek

**Comment by karlkurzer** [comment]
Hey Karsten,

thanks for looking into this.

The simplest fix would be to avoid `getCoinGeckoIdForTicker()`.

Since many crypto currencies carry the same symbol this can't work. Removing that function call should solve the problem, then it can just use the actual id (which can be easily found here: https://api.coingecko.com/api/v3/coins/list).
https://github.com/buchen/portfolio/blob/be8ebebcc2c0d2c1324819b2c5537e4773590adc/name.abuchen.portfolio/src/name/abuchen/portfolio/online/impl/CoinGeckoQuoteFeed.java#L140

**Comment by karanchopraa** [comment]
Team, 
I am facing the same issue, there are two coins with the same tickers, in metamask it's fetching the other ticker, help me to resolve it.
