### ISSUE TITLE
No data from CoinGecko API for valid symbol 

### ISSUE THREAD

**Issue by photobook-hive** [portfolio-performance/portfolio#2515]
**Describe the bug**
Getting no data for a valid CoinGecko symbol

hive ist working 
hive_dollar OR HBD diddn't work   "HBD" should be the right SYMBOL 

Probably the UPERCASE is the problem?

Both request are valid and i'm getting data.... inside of the App hive_dollar dont work

https://api.coingecko.com/api/v3/coins/hive/market_chart?vs_currency=EUR&days=62&interval=daily
https://api.coingecko.com/api/v3/coins/hive_dollar/market_chart?vs_currency=EUR&days=62&interval=daily

Original JSON output from CoinGecko API "List Coins"
  },
  {
    "id": "hive",
    "symbol": "hive",
    "name": "Hive"
  },
  {
    "id": "hive_dollar",
    "symbol": "HBD",
    "name": "Hive Dollar"
  },
  {

**Comment by photobook-hive** [comment]
I think i got it. It is a UPPER / LOWER CASE problem.

Symbol is "HBD" but the program change it to LOWERCASE "hbd" and this ist not Valid.

Tue Nov 09 12:03:30 CET 2021
Ticker-Symbol fehlt für Wertpapier hbd

java.io.IOException: Ticker-Symbol fehlt für Wertpapier hbd

	at name.abuchen.portfolio.online.impl.CoinGeckoQuoteFeed.getCoinGeckoIdForTicker(CoinGeckoQuoteFeed.java:186)

	at name.abuchen.portfolio.online.impl.CoinGeckoQuoteFeed.getHistoricalQuotes(CoinGeckoQuoteFeed.java:140)

	at name.abuchen.portfolio.online.impl.CoinGeckoQuoteFeed.getLatestQuote(CoinGeckoQuoteFeed.java:53)

	at name.abuchen.portfolio.ui.jobs.UpdateQuotesJob$1.run(UpdateQuotesJob.java:234)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kasch-code** [comment]
Thanks for pointing this out.  I missed that there are currencies which include upper case letters in their ticker symbol.

I implemented to lower case conversion in the first place, because I prefer to have the ticker symbols in upper case letters (e.g. BTC for Bitcoin) in my lists. I suppose this may be the same for other people so I am not sure if it would be a good idea to completely get rid of the conversion.

Could you please have a look if #2464 could be a suitable workaround for your case? With this change, the internal ID "hive_dollar" can be specified in addition to the ticker symbol.
