### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by seg-on** [portfolio-performance/portfolio#2893]
Hi, 
I would like to make translation to Slovak. Can you give me a advice what is best way to do it? Is there some tool for it?
Until now i was contributing in translation via 3rd party web solution like Transifex...

**Comment by Nirus2000** [comment]
Join the translation team
1. [POEditor.com](https://poeditor.com/join/project?hash=4lYKLpEWOY)
2. Join translations
3. Login with your account
4. Start your translation in your language

Have fun....

**Comment by seg-on** [comment]
I have done it. I don't know if anyone is checking.

**Comment by Nirus2000** [comment]
Great, @buchen will be informed about this automatically.
Thanks 👍🏻

**Comment by buchen** [comment]
@seg-on I have to apologize - I had too many things on my plate and I am not always watching all issues here in Github. Thankfully @Nirus2000 pointed me to your change.

I will build a test version for you to review. Which platform build do you need?

**Comment by buchen** [comment]
And adding a word of explanation: the synchronization of translations between poeditor and github is something that I have to trigger manually. I have scripts for this (in the releng folder) but it is something I usually do before a release. Adding a new language is a completely new configuration. I do not do this automatically because I do think that users do not want partially translated applications - it is either English or the local language but ideally not a mix. That's why I missed the new language...

**Comment by buchen** [comment]
And one more thing: Java supports special keywords such as ```choice``` if you want to pick one label based on something. Let's take ```LabelReportingPeriodMonths``` as an example. The original version is:
```
{0,choice,0#|1#1 month|1<{0,number} months}
```
telling PP to use the label "1 month" if the number is one, otherwise the label "{0,number} months". the values for "choice" must not be translated.

I'll try to fix them locally as I can more easily search and replace.

**Comment by seg-on** [comment]
Hi @buchen, thanks for your work. I assumed that adding a new language would require more work on your side.
I translated it from English and then compared it with Czech. But I think that there will definitely still be a few mistakes.
I'm use PP on Windows.

**Comment by seg-on** [comment]
> telling PP to use the label "1 month" if the number is one, otherwise the label "{0,number} months". the values for "choice" must not be translated. It should read

Are you mean, that I translated the word "choice" in POEditor? Is that a problem? I can not remember. It's been two months.
If yes, I'll be careful next time.
If I made more mistakes, write them to me so that I can avoid them in the future. :)

**Comment by buchen** [comment]
> I'm use PP on Windows.

I have uploaded a build that include your Slovak translation: https://www.dropbox.com/s/29a4u3w4jmgsxso/PortfolioPerformance-distro-0.59.2-SNAPSHOT-win32.win32.x86_64.zip?dl=0

It is nothing but the build of the current master branch. Try to give it a go. You can unzip it in any directory and use it next to your normal installation. If the language is not picked up directly, use the language picker in the preferences

**Comment by seg-on** [comment]
May I make changes and correction in POEditor?
Is my bad translation of "choice" still there?
Can you fix it or send me the bad strings? I will find them and fix them.

**Comment by buchen** [comment]
> May I make changes and correction in POEditor?

yes. Let me know once you have bunch of updates, and I can provide a new build

> Is my bad translation of "choice" still there?

No, I updated the strings to reflect what the GitHub code line contains (I am syncing)

**Comment by seg-on** [comment]
OK, I made more corrections. I think it is ready for the next release.
I will post on some forums, If anyone is using PP, they can check it out and report bugs to me.
