### ISSUE TITLE
Widget icons in menu

### ISSUE THREAD

**Issue by mierin12** [portfolio-performance/portfolio#3924]
**Is your feature request related to a problem? Please describe.**
Not a technical problem, no. 
But: there are more and more widgets available, this is very great, but their names do not always give a clear idea of what the widget will look like. (do you really consistently remember the data format of _Earnings per month_ vs _Monthly earnings_ ?)

**Describe the solution you'd like**
Would it be possible to add small icons in front of their name in their menu ? I do not kwow if `MenuManager` allows this.

**Describe alternatives you've considered**
Here and there we could add more details to the widget name (_Taxonomies - Pie chart_, _Earnings from Taxonomies - Pie chart_) but I think icons would be clearer, and maybe appealing ? Making the users more curious about them and testing/using them even more. On the forum we can sometimes see "oh I did not know that this widget existed".

**Additional context**
Suggestion of how I am picturing it. I did not find a % image on iconmonstr.. The only one missing..
(for heatmap the icon could have some color to differentiate it from the "Monthly ..." tables.

![WidgetCommons](https://github.com/portfolio-performance/portfolio/assets/160436107/122166f7-bc7c-4f43-8382-f78403548f1a)
![WidgetEarnings](https://github.com/portfolio-performance/portfolio/assets/160436107/0b59b0c9-ce02-4c82-ba39-061e5c9d5385)
![WidgetPerf](https://github.com/portfolio-performance/portfolio/assets/160436107/89dffbb6-32d6-4dc4-b8b4-f4a00199594b)
![WidgetRisk](https://github.com/portfolio-performance/portfolio/assets/160436107/8db0903d-62b1-4280-962f-fa9df882d1d3)
![WidgetStatementOfAssets](https://github.com/portfolio-performance/portfolio/assets/160436107/3058e123-e1ea-4474-b5ea-3a4bda263627)
![WidgetTrades](https://github.com/portfolio-performance/portfolio/assets/160436107/2bc89cec-208e-477f-b6f7-f78ba47966e7)

Edit: MenuManager can use icon/ImageDescriptor, so technically feasible.
![Capture d'écran 2024-04-10 015423](https://github.com/portfolio-performance/portfolio/assets/160436107/d49239cd-5dca-469a-a3c3-fe7e3934cacd)

If this idea is approved, maybe we can use this topic to discuss which icon is preferred for each widget ?

**Comment by buchen** [comment]
First, I agree that adding new widgets is sub-optimal. The menu worked okay while there were few items, now it is harder to find and understand.

Second about the icons: I think it makes sense to add icons for things that are already marked with an icon (say the pie charts, line charts, etc.). I propose **not** to add icons to everything simply reasons of completeness, but pick an icon only if it reasonable depicts the purpose. Otherwise the icon might even be misleading. I removed many icons from the main menu exactly for that reason.

I was also thinking about a dialog - on the left side a tree with the widgets, on the right side a preview window of the selected widget - below that the configuration options. It could include a search field, which does not only search the name but also some kind of description. If you are interested to work on this, let me know and we can sync up.

**Comment by mierin12** [comment]
> Second about the icons: I think it makes sense to add icons for things that are already marked with an icon (say the pie charts, line charts, etc.). I propose **not** to add icons to everything simply reasons of completeness, but pick an icon only if it reasonable depicts the purpose. Otherwise the icon might even be misleading. I removed many icons from the main menu exactly for that reason.

Ok ! In the end not so many widgets could be linked to already existing icons (Donut Chart/Bar Chart/Line Chart and maybe the List one (?) for Perf Calculation/Earnings Transaction Overview) . The Earnings category would be nicely represented, but the other ones would be a bit sparse. I am getting:
![Capture d'écran 2024-04-10 214429](https://github.com/portfolio-performance/portfolio/assets/160436107/cf690e20-9c4c-45fc-88b0-c68f36be14f3)
![Capture d'écran 2024-04-10 214616](https://github.com/portfolio-performance/portfolio/assets/160436107/3266177e-6939-4f5d-ac07-d28ff0775e48)
![Capture d'écran 2024-04-10 214710](https://github.com/portfolio-performance/portfolio/assets/160436107/b70637b2-ed5d-4a2a-9f79-81e40c464e71)
(sorry for the french in the picture, when launching from IDE, PP language settings is set to Automatic, so I cannot switch the language)
Let me know if this partial widget icon-ing would be worth a PR !

> I was also thinking about a dialog - on the left side a tree with the widgets, on the right side a preview window of the selected widget - below that the configuration options. It could include a search field, which does not only search the name but also some kind of description. If you are interested to work on this, let me know and we can sync up.

Yes, icon or no icon, in the end it is the menu itself which is getting a bit unclear, so a new interface/window would be a good long term solution. A preview window would be brilliant ! If I can be of some help yes ! I am slightly afraid that I am not knowledgeable enough, but why not why not.

**Comment by Sn1kk3r5** [comment]
Hi all,

while watching the upcoming questions on the forum I'd say Icons won't help much in order to self explain functionality behind a widget.

Therefore I would prefer @buchen 's idea of having a new dialog. This would not only help to rectify the current view, but would give the opportunity of having examples and a proper description.

Cheers

**Comment by Nirus2000** [comment]
See... https://github.com/portfolio-performance/portfolio/pull/3130#issuecomment-1399430259 and follow for a better understanding, as I also wanted to add the icons to the main menu myself.
