### ISSUE TITLE
Allow different currencies when transacting with a deposit account in a currency that is the same as currency of instrument

### ISSUE THREAD

**Issue by kgoderis** [portfolio-performance/portfolio#4107]
When using a USD deposit account to transact a stock in USD, then the debit/credit not is set in USD. However, sometimes taxes are charged in the local currency.

For example, with my broker in (keytradebank.com), when transacting USD stocks, the fees are USD, but the taxes are always accounted for in EUR (since the the tax authorities collect in the  "local" currency). So, when selling USD stocks, the proceeds would go as USD to an USD Deposit Account, however, local taxes are collected in EUR (but converted USD using the transaction exchange rate, and then deducted from the debit note in USD)

**Comment by Nirus2000** [comment]
Hallo @kgoderis 

Please watch the tutorial video carefully and post a "*complete*" PDF debug.

- Otherwise, please do not change or delete any other data.
- The personal data must be replaced 1 to 1.
- Other changes, such as replacing the date or similar, are also counterproductive.
- **!! ONLY YOUR OWN PERSONAL DATA !!!
- **No PDF's which are converted from a browser or similar to PDF**
- **No self-scanned paper slips**

z. B.
- *Name → Max Mustermann and so on...*
- *Address → Blumenstraße*
- IBAN and deposit numbers: The numbers 1 to 1.*

No more and no less... One post per PDF debug please. 
End.

**Video-Tutorial:**
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren

Translated with DeepL.com (free version)

**Comment by Nirus2000** [comment]
Look in PP Forum.... https://forum.portfolio-performance.info/t/pdf-import-from-keytrade/19238

**Comment by kgoderis** [comment]
@Nirus2000 Intresting, I was not aware one could import PDFs !
