### ISSUE TITLE
Selling with negative amount not supported

### ISSUE THREAD

**Issue by Luensche** [portfolio-performance/portfolio#4141]
**Describe the bug**
I would like to enter a share sale with a negative return. This prevents an error message (see screenshot).

**To Reproduce**
Buy 200 shares of GB00B1CKQD97 on 15/09/17 at a price of € 0.02 + € 6 order fees.
Sale of the same on 14/06/2024 at a price of € 0.0005 + € 6 order fees (see screenshot).

**Expected behavior**
Negative amounts can be credited. The share profit is reduced by taxes and fees and the allocation is maintained.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/94c8cb74-9d9d-4cd1-83e8-2d0598c135b2)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS] Linux
 - Version [e.g. 0.47.0] 0.69.0

**Comment by Luensche** [comment]
Seems related to #3013.

**Comment by Luensche** [comment]
@Nirus2000 In which version will be the fix included?

**Comment by Nirus2000** [comment]
Hello,

You have two options...

- Look at my answer in the link #3013  of the post before mine.
- If the transaction is to be imported via PDF document, then we need a PDF debug.

Regards
Alex

**Comment by Luensche** [comment]
I looked at your answer, but then it is not completed. You won't fix the bug.

And it is surely a bug. It is one transaction, so all should be inserted at the same place.

Why are negative amounts not allowed?

**Comment by Nirus2000** [comment]
Hello,
Not everything you find as a mistake is a mistake. It's just not an error, but in accounting terms it has to be broken in differently.
Just as two transactions, as already stated in my answer.

**Comment by Luensche** [comment]
Hi,
but then I don't understand the concept behind it. Why can I enter order fees if they reduce my profit but it still exists? What is the difference to a negative profit, i.e. a loss?

Even if I can enter it differently, it seems obvious to me that it belongs here. It is not a normal fee, but an order-specific one.

**Comment by Luensche** [comment]
@Nirus2000 How can I create a fee transaction? I have not such an option in 0.69.1.

![image](https://github.com/user-attachments/assets/d26e5b8e-c3d8-43d9-8b13-9d304bf0178b)

**Comment by Nirus2000** [comment]
Hello
I will be happy to answer your questions, but just go to the [Portfolio Performance Forum](https://forum.portfolio-performance.info/). 
There are many supporters there who will answer your questions.

> Hi,
but then I don't understand the concept behind it. Why can I enter order fees if they reduce my profit but it still exists? What is the difference to a negative profit, i.e. a loss?

Because you make a (total) loss without a profit, as the fees exceed the proceeds. And this is also the core instrument of PP to make this visible.
You don't make a profit, you make a total loss. 
Please note that we are talking about booking/bank transactions, not right pocket to left pocket. 
After all, it is actually a sale that is credited to you with 0.00 €.

> Even if I can enter it differently, it seems obvious to me that it belongs here.

The ticket has been closed. **We wont fix it**, because it is not integrated in the concept of PP or will be in the future. 
It is incorrect from a calculation point of view and must be posted in two transactions so that the calculations for performance are correctly reflected.

![grafik](https://github.com/user-attachments/assets/5bc70729-878b-4b79-b414-85c8a7867d0c)


Finally closed.
Mark as explanation.
