### ISSUE TITLE
Possibility of displaying real and calculated Quote value.

### ISSUE THREAD

**Issue by NMV0** [portfolio-performance/portfolio#4197]
**Problem:**
I opened this issue following an observation that I thought was a bug. Described here: #4196 .

When Buying a Securities or Editing a transaction, and Shares and Quote doesn't produce a round number, the value of the Quote is modified compare to the original entered value (with no manual override possible). When you go on the record and Edit Transaction..., you can modify the wrong value and save the Quote, but the modification of the value doesn't apply, the Quote price is still the same and not the one I wish. Besides the rounding, the biggest problem is that it distorts my **transaction history which is no longer a source of truth** (even before calculation/statistics).

Having the real value recorded would be a good thing for **posterity, history and traceability of transactions**.

**Solution:**
We could have the display of the value used (calculated by PP), and the real value only for display if needed for history.
The value displayed and entered in the transaction field would always be the real value manually entered, and a non-editable field would indicate the value used by PP if it is different from the one entered.

What do you think about this? Have other people encountered this problem?

**Comment by pfalcon** [comment]
For a transaction, PP records its total amount and number of "shares". The price (or "quote") is calculated based on these parameters, and is absolutely **real**, modulo precision/rounding limitations of computer systems. PP doesn't record any "quote" with a buy/sell transactions, because it's superfluous.

The whole situation is akin to: You go to shop and ask "How much is sugar?" - "100 per kilo" - "1.5kg please" - "give me 140". The real price is 93.(3) here, and the figure of 100 is irrelevant for the transaction. It may be relevant for "historical quotes", and PP records those separately from actual transactions (albeit at the day granularity and as a single value, while actual market prices are always a range), so you for example can see that you bought below/above the market price.

So again, PP doesn't record any "price" for transactions, but each transaction has a free-form "note" field, where you can put arbitrary information, for example, some "quote".
