### ISSUE TITLE
Font formatting Timeline Chart ToolTip not working

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#4318]
Not working
Could it be that the “hint” is not working correctly?
It should be smaller and in italics, right?

After -> 18e18d8f6600b57224c5853bbef7a329f66d703c

Problem see in pictures: 
#4298
#4297

**Comment by mierin12** [comment]
Hello Nirus, I do not remember ever seeing italic in the tooltip but maybe I am not remembering correctly. Do you have a example of the expected display ?

Otherwise on the same topic, I was wondering if the setting '# of decimal displayed for calculated quote' should be applied in the tooltip of securities chart. I would say yes ? Very easy fix but I was unsure if this would negatively impact people with cryptos.

**Comment by Nirus2000** [comment]
Hello @mierin12 
thank you for the feedback. Previously this was displayed correctly.
The numbers and their length should definitely remain as they are. However, as in the settings, these should actually work after X places after the comma. Why this does not work is probably because everything is formatted as a quote.

![grafik](https://github.com/user-attachments/assets/564c5bbf-6b78-4641-ac9b-75946dff51d9)


![grafik](https://github.com/user-attachments/assets/575b260c-8e1a-4f45-9ba9-468e48873fad)

Also, the ToolTip does not look good in general. It is too long and impractical.
The text should be decided according to OS Platform.
If Win ... then 'Alt' ... for MacOS just 'Option' ... and so on.
It could be a practical xxxxUtils.java class.
