### ISSUE TITLE
TradegateAGPDFExtractor.java fails to recognize "Abgeführte Kirchensteuer"

### ISSUE THREAD

**Issue by PeterSlickers** [portfolio-performance/portfolio#4338]
**Describe the bug**
PDF import of "Verkaufsabrechnung" issued by Tradegate AG results in a distorted booking. The position "Kirchensteuer" is not recognized. Instead, the stock price is deminished arbitrarily.

**To Reproduce**
The PDF document from Tradegate AG was normalized to pure text, the respective line in this text is

  `Abgeführte Kirchensteuer -0,63 EUR`

**Presumable root cause**
The regular expression utilized to recognize "Abgeführte Kirchensteuer" comprises a typo:

```
.match("^Abgef.hrter Kirchensteuer \\-(?<tax>[\\.,\\d]+) (?<currency>[\\w]{3})$") //
-------------------^

```

**Comment by Nirus2000** [comment]
Hello @PeterSlickers 
For all changes we need a PDF-Debug.
Please watch the tutorial video carefully and post a “*complete*” PDF debug.

- Otherwise, please do not change or delete any other data.
- The personal data must be replaced 1 to 1.
- Other changes, such as replacing the date or similar, are also counterproductive.
- **!! ONLY YOUR OWN PERSONAL DATA !!!
- **No PDFs which are converted to PDF from a browser or similar**
- **No self-scanned paper slips**

z. B.
- *Name → Max Mustermann and so on...*
- *Address → Blumenstraße*
- IBAN and deposit numbers: The numbers 1 to 1.*

No more and no less... One post per PDF debug please. 
End.

**Video tutorial:**
[Extract PDF documents for debugging](https://help.portfolio-performance.info/en/how-to/requesting-new-importer/)

Regards
Alex
