### ISSUE TITLE
Cannot set language to English and Country to Italy in Settings

### ISSUE THREAD

**Issue by livigni** [portfolio-performance/portfolio#4414]
**Describe the bug**
Instead of using Italian as language, I would like to set "English". Unfortunately, I cannot chose "Italy" as country (see screen below).

**To Reproduce**
1. Go to "Settings"
2. Click on 'Presentation'
3. Scroll down to 'Language'
4. Set as "English"
5. "Italy" not listed in "Country" (if select "Italian" in Language, Italy does show up in Country).

**Screenshots**
<img width="658" alt="image" src="https://github.com/user-attachments/assets/1c8f9985-623d-4b63-8642-2bb9694e63c5" />

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.72.2

**Comment by Morpheus1w3** [comment]
I'm afraid but this won't be possible as the language vs. country assignment is defined by Java/Oracle:
https://www.oracle.com/java/technologies/javase/jdk21-suported-locales.html

**Comment by buchen** [comment]
I agree with @Morpheus1w3. The default Java setup does not support this.

One could extend the JRE by a custom locale (here: en_IT) and provide custom NumberFormatProvider - see here https://stackoverflow.com/a/2283459 - not sure if you want to do the effort

There seems to be also a dynamic extension mechanism which is deprecated (but probably still works because you can control the command line argument): https://stackoverflow.com/a/70938018

**Comment by buchen** [comment]
Closing because I do not plan to support this edge case in the project.
