### ISSUE TITLE
Filtern von Transaktionen á la Excel

### ISSUE THREAD

**Issue by megabugman** [portfolio-performance/portfolio#465]
Anhängig von der Anzahl der Transaktionen verliert man schon mal den Überblick.
Mit Hilfe eines Filters ließe sich dies leicht ändern und damit zB nur Einlagen, Zinsen oder bestimmte Wertpapiere anzuzeigen. 
![filter](https://cloud.githubusercontent.com/assets/17204819/13620366/5f6950f8-e58f-11e5-96f8-96506c095c9a.png)

**Comment by mierin12** [comment]
Done since [release 0.61.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.61.0) with https://github.com/portfolio-performance/portfolio/pull/3152 for All Transactions view.
Expanded to account's transaction pane on [release 0.69.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.69.0) with https://github.com/portfolio-performance/portfolio/pull/3985
